# Generated by Django 2.2.17 on 2021-01-25 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Danie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
                ('dataDodaniaDania', models.DateTimeField(auto_now_add=True)),
                ('przepis', models.CharField(max_length=2500)),
                ('czasPrzygotowania', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=14)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danie', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('plec', models.CharField(choices=[('M', 'Mezczyzna'), ('K', 'Kobieta')], default='M', max_length=2)),
                ('adres', models.CharField(max_length=45)),
                ('dataUrodzenia', models.DateField()),
                ('dataRejestracji', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='RodzajDan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ilosc', models.IntegerField()),
                ('danie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienie', to='restauracja.Danie')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienie', to='restauracja.Klient')),
            ],
        ),
        migrations.AddField(
            model_name='danie',
            name='rodzajDania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danie', to='restauracja.RodzajDan'),
        ),
    ]
