# Generated by Django 2.2.17 on 2021-01-25 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restauracja', '0002_auto_20201203_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='RodzajDan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.AlterModelOptions(
            name='danie',
            options={'ordering': ('nazwa',)},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('nazwisko',)},
        ),
        migrations.RemoveField(
            model_name='danie',
            name='idDanie',
        ),
        migrations.RemoveField(
            model_name='danie',
            name='restauracja',
        ),
        migrations.RemoveField(
            model_name='danie',
            name='zamowienie',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='idKlient',
        ),
        migrations.RemoveField(
            model_name='klient',
            name='nrTelefonu',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='dania',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='dataZamowienia',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='idZamowienie',
        ),
        migrations.RemoveField(
            model_name='zamowienie',
            name='kwota',
        ),
        migrations.AddField(
            model_name='danie',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='danie', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danie',
            name='czasPrzygotowania',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danie',
            name='dataDodaniaDania',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='danie',
            name='przepis',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='dataRejestracji',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='dataUrodzenia',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='imie',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='nazwisko',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='klient',
            name='plec',
            field=models.CharField(choices=[('M', 'Mezczyzna'), ('K', 'Kobieta')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='danie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zamowienie', to='restauracja.Danie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='ilosc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='danie',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamowienie', to='restauracja.Klient'),
        ),
        migrations.DeleteModel(
            name='Platnosc',
        ),
        migrations.DeleteModel(
            name='Restauracja',
        ),
        migrations.AddField(
            model_name='danie',
            name='rodzajDania',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='danie', to='restauracja.RodzajDan'),
            preserve_default=False,
        ),
    ]
